export type ProductDataProps = {
    id: number;
    category: "Fashion" | "Tech" | "Home & Living";
    name: string;
    description: string;
    img: string;
    alt: string;
    price: number;
    stock: number;
}

export const productData : ProductDataProps[] = [
    {
        id: 1,
        category: "Tech",
        name: "camera",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/camera.png",
        alt: "camera",
        price: 7500000,
        stock: 27,
    },
    {
        id: 2,
        category: "Home & Living",
        name: "Meja Jam",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/meja-jam.png",
        alt: "meja jam",
        price: 250000,
        stock: 187,
    },
    {
        id: 3,
        category: "Tech",
        name: "Laptop",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/macbook-pro.png",
        alt: "macbook pro",
        price: 4500000,
        stock: 76,
    },
    {
        id: 4,
        category: "Home & Living",
        name: "Bingkai Foto",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/bingkai-foto.png",
        alt: "Bingkai Foto",
        price: 45000,
        stock: 236,
    },
    {
        id: 5,
        category: "Home & Living",
        name: "Mesin Jahit",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/mesin-jahit.png",
        alt: "Mesin Jahit",
        price: 170000,
        stock: 97,
    },
    {
        id: 6,
        category: "Fashion",
        name: "Pakaian Pria",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/pakaian-pria.png",
        alt: "Pakaian Pria",
        price: 125000,
        stock: 439,
    },
    {
        id: 7,
        category: "Home & Living",
        name: "Peralatan Dapur",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/peralatan-dapur.png",
        alt: "Peralatan Dapur",
        price: 15000,
        stock: 221,
    },
    {
        id: 8,
        category: "Fashion",
        name: "Sepatu Ungu",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/sepatu-ungu.png",
        alt: "Sepatu Ungu",
        price: 2500000,
        stock: 123,
    },
    {
        id: 9,
        category: "Home & Living",
        name: "sofa",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/sofa.png",
        alt: "sofa",
        price: 3200000,
        stock: 21,
    },
    {
        id: 10,
        category: "Home & Living",
        name: "Topi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/topi.png",
        alt: "topi",
        price: 37000,
        stock: 321,
    },
    {
        id: 11,
        category: "Tech",
        name: "Gopro",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/gopro.jpg",
        alt: "gopro",
        price: 5300000,
        stock: 24,
    },
    {
        id: 12,
        category: "Fashion",
        name: "Jaket Hoodie",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/jaket-hoodie.png",
        alt: "jaket hoodie",
        price: 225000,
        stock: 376,
    },
    {
        id: 13,
        category: "Fashion",
        name: "Sepatu Bot Kulit",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/sepatu-bot-kulit.png",
        alt: "sepatu bot kulit",
        price: 3350000,
        stock: 156,
    },
    {
        id: 14,
        category: "Tech",
        name: "Smart Watch",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/smart-watch.jpg",
        alt: "Smart Watch",
        price: 750000,
        stock: 289,
    },
    {
        id: 15,
        category: "Tech",
        name: "Earphone",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/earphone.jpg",
        alt: "earphone",
        price: 375000,
        stock: 211,
    },
    {
        id: 16,
        category: "Tech",
        name: "Tablet",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/tablet.png",
        alt: "tablet",
        price: 3750000,
        stock: 97,
    },
    {
        id: 17,
        category: "Fashion",
        name: "Tas Kulit",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/tas-kulit.png",
        alt: "tas kulit",
        price: 345000,
        stock: 324,
    },
    {
        id: 18,
        category: "Tech",
        name: "Virtual Reality",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/virtual-reality.png",
        alt: "virtual reality",
        price: 5650000,
        stock: 32,
    },
    {
        id: 19,
        category: "Tech",
        name: "Headphone",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus dicta tenetur vero reiciendis ratione ducimus laudantium facilis tempore nam numquam.",
        img:"/product/headphone.png",
        alt: "headphone",
        price: 420000,
        stock: 229,
    },
]